version: '3.8'

services:
  db:
    image: postgres:15
    container_name: facturas_db
    restart: always
    environment:
      POSTGRES_DB: facturasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Caasd21215@@
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app_facturas
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_facturas
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgre@example.com
      PGADMIN_DEFAULT_PASSWORD: Caasd21215@@
    ports:
      - "5051:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: