# Generated by Django 5.2 on 2025-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturapp', '0002_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rnc',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula', 'Cédula'), ('RNC', 'RNC')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
