# Generated by Django 5.2 on 2025-05-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturapp', '0003_rename_rnc_cliente_documento_cliente_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='documento',
            new_name='cedula',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_documento',
        ),
    ]
